name: Go WebSockify
on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - master
jobs:
  amd64_job:
    name: Go-${{matrix.GOVER}}/amd64
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        GOVER: ['1.15', '1.14', '1.13', '1.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go-${{ matrix.GOVER }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.GOVER }}